import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export async function GET() {
  const isCloud = Boolean(process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME);
  const envPath = path.resolve(process.cwd(), ".env.local");
  const hasLocalEnv = !isCloud && fs.existsSync(envPath);

  return NextResponse.json({
    success: true,
    isLocal: !isCloud,
    hasLocalEnv,
    envStatus: {
      groqConfigured: Boolean(process.env.GROQ_API_KEY && !process.env.GROQ_API_KEY.includes("placeholder")),
      razorpayConfigured: Boolean(process.env.RAZORPAY_KEY_ID && !process.env.RAZORPAY_KEY_ID.includes("placeholder")),
      hmacConfigured: Boolean(process.env.RECOURSE_HMAC_SECRET),
    },
  });
}

export async function POST(req: NextRequest) {
  try {
    const isCloud = Boolean(process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME);
    const body = await req.json();
    const { groqApiKey, razorpayKeyId, razorpayKeySecret, recourseHmacSecret } = body;

    // If running in cloud (Vercel/Lambda), filesystem is read-only, so keys are maintained in client localStorage
    if (isCloud) {
      return NextResponse.json({
        success: true,
        mode: "cloud",
        savedLocally: false,
        message: "Cloud environment detected. Keys applied to your active browser session.",
      });
    }

    // Local environment: write or update .env.local
    const envPath = path.resolve(process.cwd(), ".env.local");
    const hmacVal = recourseHmacSecret || "recourse_super_secret_production_key_32_chars";

    const envContent = [
      `# Generated by Recourse Setup Console on ${new Date().toISOString()}`,
      `GROQ_API_KEY=${groqApiKey || ""}`,
      `RAZORPAY_KEY_ID=${razorpayKeyId || ""}`,
      `RAZORPAY_KEY_SECRET=${razorpayKeySecret || ""}`,
      `RECOURSE_HMAC_SECRET=${hmacVal}`,
      "",
    ].join("\n");

    fs.writeFileSync(envPath, envContent, "utf-8");

    // Also update current process.env in memory for the local server
    if (groqApiKey) process.env.GROQ_API_KEY = groqApiKey;
    if (razorpayKeyId) process.env.RAZORPAY_KEY_ID = razorpayKeyId;
    if (razorpayKeySecret) process.env.RAZORPAY_KEY_SECRET = razorpayKeySecret;
    if (hmacVal) process.env.RECOURSE_HMAC_SECRET = hmacVal;

    return NextResponse.json({
      success: true,
      mode: "local",
      savedLocally: true,
      message: ".env.local generated and updated successfully on your PC.",
    });
  } catch (error: any) {
    console.error("Failed to save local environment:", error);
    return NextResponse.json(
      { success: false, error: "Failed to write local environment file", details: error.message },
      { status: 500 }
    );
  }
}
